In [70]:
print("hello")

hello

In [71]:
import torch
from torch.nn import Linear
import sklearn
from datasets import Dataset
import pandas  as pd
import numpy as np

In [72]:
df=pd.read_csv('../datasets/sp500/sp500_stocks.csv')

In [73]:
print(df.head())
print(df.info())
print(df.describe())

         date       open       high        low      close     volume symbol
0  2000-01-03  46.873742  46.985347  40.103091  42.855995  4674353.0      A
1  2000-01-04  40.549510  40.995929  38.540636  39.582275  4765083.0      A
2  2000-01-05  39.433461  39.582268  35.899333  37.126976  5758642.0      A
3  2000-01-06  36.680559  36.903768  34.597280  35.713322  2534434.0      A
4  2000-01-07  35.155306  39.247459  35.118107  38.689438  2819626.0      A
<class 'pandas.DataFrame'>
RangeIndex: 2929342 entries, 0 to 2929341
Data columns (total 7 columns):
 #   Column  Dtype
---  ------  -----
 0   date    str
 1   open    float64
 2   high    float64
 3   low     float64
 4   close   float64
 5   volume  float64
 6   symbol  str
dtypes: float64(5), str(2)
memory usage: 193.2 MB
None
               open          high           low         close        volume
count  2.929342e+06  2.929342e+06  2.929342e+06  2.929342e+06  2.929342e+06
mean   7.494689e+01  7.584039e+01  7.403613e+01  7.495729e+01  8.510198e+06
std    1.950922e+02  1.974588e+02  1.927506e+02  1.951070e+02  4.738149e+07
min    3.020800e-02  3.052100e-02  2.697900e-02  3.052100e-02  0.000000e+00
25%    1.624528e+01  1.646625e+01  1.601000e+01  1.624618e+01  9.520000e+05
50%    3.431142e+01  3.471536e+01  3.389808e+01  3.432000e+01  2.233900e+06
75%    7.708031e+01  7.795005e+01  7.619994e+01  7.708870e+01  5.425500e+06
max    9.914170e+03  9.964770e+03  9.794000e+03  9.924400e+03  9.230856e+09

In [74]:
df.isnull().sum()

date      0
open      0
high      0
low       0
close     0
volume    0
symbol    0
dtype: int64

In [75]:
df.describe()

               open          high           low         close        volume
count  2.929342e+06  2.929342e+06  2.929342e+06  2.929342e+06  2.929342e+06
mean   7.494689e+01  7.584039e+01  7.403613e+01  7.495729e+01  8.510198e+06
std    1.950922e+02  1.974588e+02  1.927506e+02  1.951070e+02  4.738149e+07
min    3.020800e-02  3.052100e-02  2.697900e-02  3.052100e-02  0.000000e+00
25%    1.624528e+01  1.646625e+01  1.601000e+01  1.624618e+01  9.520000e+05
50%    3.431142e+01  3.471536e+01  3.389808e+01  3.432000e+01  2.233900e+06
75%    7.708031e+01  7.795005e+01  7.619994e+01  7.708870e+01  5.425500e+06
max    9.914170e+03  9.964770e+03  9.794000e+03  9.924400e+03  9.230856e+09

In [76]:
import seaborn as sns
import matplotlib.pyplot as plt

In [77]:
# plt.figure(figsize=(15,5))
# plt.plot(df["date"],df["close"])
# plt.title("Closing Price")
# plt.show()

In [78]:
# plt.figure(figsize=(300,100))
# plt.plot(df["date"], df["open"], label="open")
# plt.plot(df["date"], df["high"], label="high")
# plt.plot(df["date"], df["low"], label="low")
# plt.plot(df["date"], df["close"], label="close")
# plt.legend()
# plt.show()

In [79]:
import mplfinance as mpf

In [80]:
# # Convert date column to datetime
# df["date"] = pd.to_datetime(df["date"])

# # Keep only one stock (change symbol if needed)
# stock = df[df["symbol"] == "AAPL"].copy()

# # Set date as index
# stock.set_index("date", inplace=True)

# # Sort by date
# stock.sort_index(inplace=True)

# # Plot candlestick chart with volume
# mpf.plot(
#     stock,
#     type="candle",
#     style="yahoo",
#     volume=True,
#     figsize=(16,8),
#     title="AAPL Candlestick Chart",
#     ylabel="Price",
#     ylabel_lower="Volume"
# )

In [81]:
df.duplicated().sum()

np.int64(0)

In [82]:
df=df.sort_values(["symbol","date"])
df.head()

         date       open       high        low      close     volume symbol
0  2000-01-03  46.873742  46.985347  40.103091  42.855995  4674353.0      A
1  2000-01-04  40.549510  40.995929  38.540636  39.582275  4765083.0      A
2  2000-01-05  39.433461  39.582268  35.899333  37.126976  5758642.0      A
3  2000-01-06  36.680559  36.903768  34.597280  35.713322  2534434.0      A
4  2000-01-07  35.155306  39.247459  35.118107  38.689438  2819626.0      A

In [83]:
#Feature Creation
df["return"] = df.groupby("symbol")["close"].pct_change()
df["ma20"] = df.groupby("symbol")["close"].transform(lambda x: x.rolling(20).mean())
df["volatility"] = (
    df.groupby("symbol")["return"]
      .transform(lambda x: x.rolling(20).std())
)
df.head(100)

,date,open,high,low,close,volume,symbol,return,ma20,volatility
0,2000-01-03,46.873742,46.985347,40.103091,42.855995,4674353.0,A,NaN,NaN,NaN
1,2000-01-04,40.549510,40.995929,38.540636,39.582275,4765083.0,A,-0.076389,NaN,NaN
2,2000-01-05,39.433461,39.582268,35.899333,37.126976,5758642.0,A,-0.062030,NaN,NaN
3,2000-01-06,36.680559,36.903768,34.597280,35.713322,2534434.0,A,-0.038076,NaN,NaN
4,2000-01-07,35.155306,39.247459,35.118107,38.689438,2819626.0,A,0.083334,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
95,2000-05-18,46.427336,46.985357,42.260780,42.260780,6153437.0,A,-0.089743,51.989396,0.067023
96,2000-05-19,43.265203,44.455646,39.359058,39.656670,5261093.0,A,-0.061620,51.295590,0.067380
97,2000-05-22,39.879880,40.475100,35.676123,37.126976,7820692.0,A,-0.063790,50.425078,0.067872
98,2000-05-23,36.866568,37.647799,33.667248,34.522881,5214680.0,A,-0.070140,49.472722,0.068909
99,2000-05-24,34.374072,35.676120,32.141989,35.118099,7957276.0,A,0.017241,48.494326,0.068803

In [84]:
df.isnull().sum()

date              0
open              0
high              0
low               0
close             0
volume            0
symbol            0
return          503
ma20           9551
volatility    10053
dtype: int64

In [85]:
print(df.shape)

df = df.dropna()

print(df.shape)

(2929342, 10)
(2919289, 10)

In [86]:
df.head()

,date,open,high,low,close,volume,symbol,return,ma20,volatility
20,2000-02-01,39.433473,42.856004,39.433473,42.260780,1404291.0,A,0.072710,40.177495,0.041255
21,2000-02-02,42.781595,45.534500,42.595588,45.534500,1945177.0,A,0.077465,40.475106,0.040580
22,2000-02-03,44.753264,46.278522,43.934835,46.278522,1779514.0,A,0.016340,40.932683,0.037119
23,2000-02-04,46.278512,46.278512,44.641650,45.385677,1145661.0,A,-0.019293,41.416301,0.036014
24,2000-02-07,46.241333,47.617784,45.385700,47.320175,1274277.0,A,0.042624,41.847838,0.032817

In [87]:
stock_lengths = df.groupby("symbol").size()
print(stock_lengths.describe())

count     502.000000
mean     5815.316733
std      1565.219632
min         6.000000
25%      5551.750000
50%      6644.000000
75%      6644.000000
max      6644.000000
dtype: float64

In [88]:
print(stock_lengths[stock_lengths < 100])

symbol
FDXF    6
dtype: int64

In [89]:
valid_symbols = stock_lengths[stock_lengths >= 100].index

df = df[df["symbol"].isin(valid_symbols)]

In [90]:
new_totao_stocks=df["symbol"].unique()
print(new_totao_stocks)

<ArrowStringArray>
[   'A', 'AAPL', 'ABBV', 'ABNB',  'ABT', 'ACGL',  'ACN', 'ADBE',  'ADI',
  'ADM',
 ...
   'WY', 'WYNN',  'XEL',  'XOM',  'XYL',  'XYZ',  'YUM',  'ZBH', 'ZBRA',
  'ZTS']
Length: 501, dtype: str

In [91]:
df["target_open"] = df.groupby("symbol")["open"].shift(-1)
df["target_high"] = df.groupby("symbol")["high"].shift(-1)
df["target_low"] = df.groupby("symbol")["low"].shift(-1)
df["target_close"] = df.groupby("symbol")["close"].shift(-1)

In [92]:
df.head(100)

,date,open,high,low,close,volume,symbol,return,ma20,volatility,target_open,target_high,target_low,target_close
20,2000-02-01,39.433473,42.856004,39.433473,42.260780,1404291.0,A,0.072710,40.177495,0.041255,42.781595,45.534500,42.595588,45.534500
21,2000-02-02,42.781595,45.534500,42.595588,45.534500,1945177.0,A,0.077465,40.475106,0.040580,44.753264,46.278522,43.934835,46.278522
22,2000-02-03,44.753264,46.278522,43.934835,46.278522,1779514.0,A,0.016340,40.932683,0.037119,46.278512,46.278512,44.641650,45.385677
23,2000-02-04,46.278512,46.278512,44.641650,45.385677,1145661.0,A,-0.019293,41.416301,0.036014,46.241333,47.617784,45.385700,47.320175
24,2000-02-07,46.241333,47.617784,45.385700,47.320175,1274277.0,A,0.042624,41.847838,0.032817,48.064185,48.919817,46.576130,47.022549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2000-06-16,39.396274,39.619480,36.903781,37.275795,6487699.0,A,-0.050237,40.828518,0.076176,36.978183,41.070336,36.978183,40.475113
116,2000-06-19,36.978183,41.070336,36.978183,40.475113,6811475.0,A,0.085828,40.869441,0.077393,41.033134,45.162490,40.698323,43.823238
117,2000-06-20,41.033134,45.162490,40.698323,43.823238,11718176.0,A,0.082721,41.204254,0.077597,43.674414,47.580558,43.637211,46.724926
118,2000-06-21,43.674414,47.580558,43.637211,46.724926,8977676.0,A,0.066213,41.814356,0.076060,47.468972,47.506172,44.269651,45.088081
119,2000-06-22,47.468972,47.506172,44.269651,45.088081,6733747.0,A,-0.035032,42.312855,0.076976,44.009243,46.129722,43.972044,44.716068

In [93]:
df.isnull().sum()

date              0
open              0
high              0
low               0
close             0
volume            0
symbol            0
return            0
ma20              0
volatility        0
target_open     501
target_high     501
target_low      501
target_close    501
dtype: int64

In [94]:
df.dropna(subset=["target_open","target_high",
    "target_low",
    "target_close"],
          inplace=True)
df.isnull().sum()

date            0
open            0
high            0
low             0
close           0
volume          0
symbol          0
return          0
ma20            0
volatility      0
target_open     0
target_high     0
target_low      0
target_close    0
dtype: int64

In [95]:
dates=sorted(df["date"].unique())
dates

['2000-02-01',
 '2000-02-02',
 '2000-02-03',
 '2000-02-04',
 '2000-02-07',
 '2000-02-08',
 '2000-02-09',
 '2000-02-10',
 '2000-02-11',
 '2000-02-14',
 '2000-02-15',
 '2000-02-16',
 '2000-02-17',
 '2000-02-18',
 '2000-02-22',
 '2000-02-23',
 '2000-02-24',
 '2000-02-25',
 '2000-02-28',
 '2000-02-29',
 '2000-03-01',
 '2000-03-02',
 '2000-03-03',
 '2000-03-06',
 '2000-03-07',
 '2000-03-08',
 '2000-03-09',
 '2000-03-10',
 '2000-03-13',
 '2000-03-14',
 '2000-03-15',
 '2000-03-16',
 '2000-03-17',
 '2000-03-20',
 '2000-03-21',
 '2000-03-22',
 '2000-03-23',
 '2000-03-24',
 '2000-03-27',
 '2000-03-28',
 '2000-03-29',
 '2000-03-30',
 '2000-03-31',
 '2000-04-03',
 '2000-04-04',
 '2000-04-05',
 '2000-04-06',
 '2000-04-07',
 '2000-04-10',
 '2000-04-11',
 '2000-04-12',
 '2000-04-13',
 '2000-04-14',
 '2000-04-17',
 '2000-04-18',
 '2000-04-19',
 '2000-04-20',
 '2000-04-24',
 '2000-04-25',
 '2000-04-26',
 '2000-04-27',
 '2000-04-28',
 '2000-05-01',
 '2000-05-02',
 '2000-05-03',
 '2000-05-04',
 '2000-05-05',
 '2000-05-08',
 '2000-05-09',
 '2000-05-10',
 '2000-05-11',
 '2000-05-12',
 '2000-05-15',
 '2000-05-16',
 '2000-05-17',
 '2000-05-18',
 '2000-05-19',
 '2000-05-22',
 '2000-05-23',
 '2000-05-24',
 '2000-05-25',
 '2000-05-26',
 '2000-05-30',
 '2000-05-31',
 '2000-06-01',
 '2000-06-02',
 '2000-06-05',
 '2000-06-06',
 '2000-06-07',
 '2000-06-08',
 '2000-06-09',
 '2000-06-12',
 '2000-06-13',
 '2000-06-14',
 '2000-06-15',
 '2000-06-16',
 '2000-06-19',
 '2000-06-20',
 '2000-06-21',
 '2000-06-22',
 '2000-06-23',
 '2000-06-26',
 '2000-06-27',
 '2000-06-28',
 '2000-06-29',
 '2000-06-30',
 '2000-07-03',
 '2000-07-05',
 '2000-07-06',
 '2000-07-07',
 '2000-07-10',
 '2000-07-11',
 '2000-07-12',
 '2000-07-13',
 '2000-07-14',
 '2000-07-17',
 '2000-07-18',
 '2000-07-19',
 '2000-07-20',
 '2000-07-21',
 '2000-07-24',
 '2000-07-25',
 '2000-07-26',
 '2000-07-27',
 '2000-07-28',
 '2000-07-31',
 '2000-08-01',
 '2000-08-02',
 '2000-08-03',
 '2000-08-04',
 '2000-08-07',
 '2000-08-08',
 '2000-08-09',
 '2000-08-10',
 '2000-08-11',
 '2000-08-14',
 '2000-08-15',
 '2000-08-16',
 '2000-08-17',
 '2000-08-18',
 '2000-08-21',
 '2000-08-22',
 '2000-08-23',
 '2000-08-24',
 '2000-08-25',
 '2000-08-28',
 '2000-08-29',
 '2000-08-30',
 '2000-08-31',
 '2000-09-01',
 '2000-09-05',
 '2000-09-06',
 '2000-09-07',
 '2000-09-08',
 '2000-09-11',
 '2000-09-12',
 '2000-09-13',
 '2000-09-14',
 '2000-09-15',
 '2000-09-18',
 '2000-09-19',
 '2000-09-20',
 '2000-09-21',
 '2000-09-22',
 '2000-09-25',
 '2000-09-26',
 '2000-09-27',
 '2000-09-28',
 '2000-09-29',
 '2000-10-02',
 '2000-10-03',
 '2000-10-04',
 '2000-10-05',
 '2000-10-06',
 '2000-10-09',
 '2000-10-10',
 '2000-10-11',
 '2000-10-12',
 '2000-10-13',
 '2000-10-16',
 '2000-10-17',
 '2000-10-18',
 '2000-10-19',
 '2000-10-20',
 '2000-10-23',
 '2000-10-24',
 '2000-10-25',
 '2000-10-26',
 '2000-10-27',
 '2000-10-30',
 '2000-10-31',
 '2000-11-01',
 '2000-11-02',
 '2000-11-03',
 '2000-11-06',
 '2000-11-07',
 '2000-11-08',
 '2000-11-09',
 '2000-11-10',
 '2000-11-13',
 '2000-11-14',
 '2000-11-15',
 '2000-11-16',
 '2000-11-17',
 '2000-11-20',
 '2000-11-21',
 '2000-11-22',
 '2000-11-24',
 '2000-11-27',
 '2000-11-28',
 '2000-11-29',
 '2000-11-30',
 '2000-12-01',
 '2000-12-04',
 '2000-12-05',
 '2000-12-06',
 '2000-12-07',
 '2000-12-08',
 '2000-12-11',
 '2000-12-12',
 '2000-12-13',
 '2000-12-14',
 '2000-12-15',
 '2000-12-18',
 '2000-12-19',
 '2000-12-20',
 '2000-12-21',
 '2000-12-22',
 '2000-12-26',
 '2000-12-27',
 '2000-12-28',
 '2000-12-29',
 '2001-01-02',
 '2001-01-03',
 '2001-01-04',
 '2001-01-05',
 '2001-01-08',
 '2001-01-09',
 '2001-01-10',
 '2001-01-11',
 '2001-01-12',
 '2001-01-16',
 '2001-01-17',
 '2001-01-18',
 '2001-01-19',
 '2001-01-22',
 '2001-01-23',
 '2001-01-24',
 '2001-01-25',
 '2001-01-26',
 '2001-01-29',
 '2001-01-30',
 '2001-01-31',
 '2001-02-01',
 '2001-02-02',
 '2001-02-05',
 '2001-02-06',
 '2001-02-07',
 '2001-02-08',
 '2001-02-09',
 '2001-02-12',
 '2001-02-13',
 '2001-02-14',
 '2001-02-15',
 '2001-02-16',
 '2001-02-20',
 '2001-02-21',
 '2001-02-22',
 '2001-02-23',
 '2001-02-26',
 '2001-02-27',
 '2001-02-28',
 '2001-03-01',
 '2001-03-02',
 '2001-03-05',
 '2001-03-06',
 '2001-03-07',
 '2001-03-08',
 '2001-03-09',
 '2001-03-12',
 '2001-03-13',
 '2001-03-14',
 '2001-03-15',
 '2001-03-16',
 '2001-03-19',
 '2001-03-20',
 '2001-03-21',
 '2001-03-22',
 '2001-03-23',
 '2001-03-26',
 '2001-03-27',
 '2001-03-28',
 '2001-03-29',
 '2001-03-30',
 '2001-04-02',
 '2001-04-03',
 '2001-04-04',
 '2001-04-05',
 '2001-04-06',
 '2001-04-09',
 '2001-04-10',
 '2001-04-11',
 '2001-04-12',
 '2001-04-16',
 '2001-04-17',
 '2001-04-18',
 '2001-04-19',
 '2001-04-20',
 '2001-04-23',
 '2001-04-24',
 '2001-04-25',
 '2001-04-26',
 '2001-04-27',
 '2001-04-30',
 '2001-05-01',
 '2001-05-02',
 '2001-05-03',
 '2001-05-04',
 '2001-05-07',
 '2001-05-08',
 '2001-05-09',
 '2001-05-10',
 '2001-05-11',
 '2001-05-14',
 '2001-05-15',
 '2001-05-16',
 '2001-05-17',
 '2001-05-18',
 '2001-05-21',
 '2001-05-22',
 '2001-05-23',
 '2001-05-24',
 '2001-05-25',
 '2001-05-29',
 '2001-05-30',
 '2001-05-31',
 '2001-06-01',
 '2001-06-04',
 '2001-06-05',
 '2001-06-06',
 '2001-06-07',
 '2001-06-08',
 '2001-06-11',
 '2001-06-12',
 '2001-06-13',
 '2001-06-14',
 '2001-06-15',
 '2001-06-18',
 '2001-06-19',
 '2001-06-20',
 '2001-06-21',
 '2001-06-22',
 '2001-06-25',
 '2001-06-26',
 '2001-06-27',
 '2001-06-28',
 '2001-06-29',
 '2001-07-02',
 '2001-07-03',
 '2001-07-05',
 '2001-07-06',
 '2001-07-09',
 '2001-07-10',
 '2001-07-11',
 '2001-07-12',
 '2001-07-13',
 '2001-07-16',
 '2001-07-17',
 '2001-07-18',
 '2001-07-19',
 '2001-07-20',
 '2001-07-23',
 '2001-07-24',
 '2001-07-25',
 '2001-07-26',
 '2001-07-27',
 '2001-07-30',
 '2001-07-31',
 '2001-08-01',
 '2001-08-02',
 '2001-08-03',
 '2001-08-06',
 '2001-08-07',
 '2001-08-08',
 '2001-08-09',
 '2001-08-10',
 '2001-08-13',
 '2001-08-14',
 '2001-08-15',
 '2001-08-16',
 '2001-08-17',
 '2001-08-20',
 '2001-08-21',
 '2001-08-22',
 '2001-08-23',
 '2001-08-24',
 '2001-08-27',
 '2001-08-28',
 '2001-08-29',
 '2001-08-30',
 '2001-08-31',
 '2001-09-04',
 '2001-09-05',
 '2001-09-06',
 '2001-09-07',
 '2001-09-10',
 '2001-09-17',
 '2001-09-18',
 '2001-09-19',
 '2001-09-20',
 '2001-09-21',
 '2001-09-24',
 '2001-09-25',
 '2001-09-26',
 '2001-09-27',
 '2001-09-28',
 '2001-10-01',
 '2001-10-02',
 '2001-10-03',
 '2001-10-04',
 '2001-10-05',
 '2001-10-08',
 '2001-10-09',
 '2001-10-10',
 '2001-10-11',
 '2001-10-12',
 '2001-10-15',
 '2001-10-16',
 '2001-10-17',
 '2001-10-18',
 '2001-10-19',
 '2001-10-22',
 '2001-10-23',
 '2001-10-24',
 '2001-10-25',
 '2001-10-26',
 '2001-10-29',
 '2001-10-30',
 '2001-10-31',
 '2001-11-01',
 '2001-11-02',
 '2001-11-05',
 '2001-11-06',
 '2001-11-07',
 '2001-11-08',
 '2001-11-09',
 '2001-11-12',
 '2001-11-13',
 '2001-11-14',
 '2001-11-15',
 '2001-11-16',
 '2001-11-19',
 '2001-11-20',
 '2001-11-21',
 '2001-11-23',
 '2001-11-26',
 '2001-11-27',
 '2001-11-28',
 '2001-11-29',
 '2001-11-30',
 '2001-12-03',
 '2001-12-04',
 '2001-12-05',
 '2001-12-06',
 '2001-12-07',
 '2001-12-10',
 '2001-12-11',
 '2001-12-12',
 '2001-12-13',
 '2001-12-14',
 '2001-12-17',
 '2001-12-18',
 '2001-12-19',
 '2001-12-20',
 '2001-12-21',
 '2001-12-24',
 '2001-12-26',
 '2001-12-27',
 '2001-12-28',
 '2001-12-31',
 '2002-01-02',
 '2002-01-03',
 '2002-01-04',
 '2002-01-07',
 '2002-01-08',
 '2002-01-09',
 '2002-01-10',
 '2002-01-11',
 '2002-01-14',
 '2002-01-15',
 '2002-01-16',
 '2002-01-17',
 '2002-01-18',
 '2002-01-22',
 '2002-01-23',
 '2002-01-24',
 '2002-01-25',
 '2002-01-28',
 '2002-01-29',
 '2002-01-30',
 '2002-01-31',
 '2002-02-01',
 '2002-02-04',
 '2002-02-05',
 '2002-02-06',
 '2002-02-07',
 '2002-02-08',
 '2002-02-11',
 '2002-02-12',
 '2002-02-13',
 '2002-02-14',
 '2002-02-15',
 '2002-02-19',
 '2002-02-20',
 '2002-02-21',
 '2002-02-22',
 '2002-02-25',
 '2002-02-26',
 '2002-02-27',
 '2002-02-28',
 '2002-03-01',
 '2002-03-04',
 '2002-03-05',
 '2002-03-06',
 '2002-03-07',
 '2002-03-08',
 '2002-03-11',
 '2002-03-12',
 '2002-03-13',
 '2002-03-14',
 '2002-03-15',
 '2002-03-18',
 '2002-03-19',
 '2002-03-20',
 '2002-03-21',
 '2002-03-22',
 '2002-03-25',
 '2002-03-26',
 '2002-03-27',
 '2002-03-28',
 '2002-04-01',
 '2002-04-02',
 '2002-04-03',
 '2002-04-04',
 '2002-04-05',
 '2002-04-08',
 '2002-04-09',
 '2002-04-10',
 '2002-04-11',
 '2002-04-12',
 '2002-04-15',
 '2002-04-16',
 '2002-04-17',
 '2002-04-18',
 '2002-04-19',
 '2002-04-22',
 '2002-04-23',
 '2002-04-24',
 '2002-04-25',
 '2002-04-26',
 '2002-04-29',
 '2002-04-30',
 '2002-05-01',
 '2002-05-02',
 '2002-05-03',
 '2002-05-06',
 '2002-05-07',
 '2002-05-08',
 '2002-05-09',
 '2002-05-10',
 '2002-05-13',
 '2002-05-14',
 '2002-05-15',
 '2002-05-16',
 '2002-05-17',
 '2002-05-20',
 '2002-05-21',
 '2002-05-22',
 '2002-05-23',
 '2002-05-24',
 '2002-05-28',
 '2002-05-29',
 '2002-05-30',
 '2002-05-31',
 '2002-06-03',
 '2002-06-04',
 '2002-06-05',
 '2002-06-06',
 '2002-06-07',
 '2002-06-10',
 '2002-06-11',
 '2002-06-12',
 '2002-06-13',
 '2002-06-14',
 '2002-06-17',
 '2002-06-18',
 '2002-06-19',
 '2002-06-20',
 '2002-06-21',
 '2002-06-24',
 '2002-06-25',
 '2002-06-26',
 '2002-06-27',
 '2002-06-28',
 '2002-07-01',
 '2002-07-02',
 '2002-07-03',
 '2002-07-05',
 '2002-07-08',
 '2002-07-09',
 '2002-07-10',
 '2002-07-11',
 '2002-07-12',
 '2002-07-15',
 '2002-07-16',
 '2002-07-17',
 '2002-07-18',
 '2002-07-19',
 '2002-07-22',
 '2002-07-23',
 '2002-07-24',
 '2002-07-25',
 '2002-07-26',
 '2002-07-29',
 '2002-07-30',
 '2002-07-31',
 '2002-08-01',
 '2002-08-02',
 '2002-08-05',
 '2002-08-06',
 '2002-08-07',
 '2002-08-08',
 '2002-08-09',
 '2002-08-12',
 '2002-08-13',
 '2002-08-14',
 '2002-08-15',
 '2002-08-16',
 '2002-08-19',
 '2002-08-20',
 '2002-08-21',
 '2002-08-22',
 '2002-08-23',
 '2002-08-26',
 '2002-08-27',
 '2002-08-28',
 '2002-08-29',
 '2002-08-30',
 '2002-09-03',
 '2002-09-04',
 '2002-09-05',
 '2002-09-06',
 '2002-09-09',
 '2002-09-10',
 '2002-09-11',
 '2002-09-12',
 '2002-09-13',
 '2002-09-16',
 '2002-09-17',
 '2002-09-18',
 '2002-09-19',
 '2002-09-20',
 '2002-09-23',
 '2002-09-24',
 '2002-09-25',
 '2002-09-26',
 '2002-09-27',
 '2002-09-30',
 '2002-10-01',
 '2002-10-02',
 '2002-10-03',
 '2002-10-04',
 '2002-10-07',
 '2002-10-08',
 '2002-10-09',
 '2002-10-10',
 '2002-10-11',
 '2002-10-14',
 '2002-10-15',
 '2002-10-16',
 '2002-10-17',
 '2002-10-18',
 '2002-10-21',
 '2002-10-22',
 '2002-10-23',
 '2002-10-24',
 '2002-10-25',
 '2002-10-28',
 '2002-10-29',
 '2002-10-30',
 '2002-10-31',
 '2002-11-01',
 '2002-11-04',
 '2002-11-05',
 '2002-11-06',
 '2002-11-07',
 '2002-11-08',
 '2002-11-11',
 '2002-11-12',
 '2002-11-13',
 '2002-11-14',
 '2002-11-15',
 '2002-11-18',
 '2002-11-19',
 '2002-11-20',
 '2002-11-21',
 '2002-11-22',
 '2002-11-25',
 '2002-11-26',
 '2002-11-27',
 '2002-11-29',
 '2002-12-02',
 '2002-12-03',
 '2002-12-04',
 '2002-12-05',
 '2002-12-06',
 '2002-12-09',
 '2002-12-10',
 '2002-12-11',
 '2002-12-12',
 '2002-12-13',
 '2002-12-16',
 '2002-12-17',
 '2002-12-18',
 '2002-12-19',
 '2002-12-20',
 '2002-12-23',
 '2002-12-24',
 '2002-12-26',
 '2002-12-27',
 '2002-12-30',
 '2002-12-31',
 '2003-01-02',
 '2003-01-03',
 '2003-01-06',
 '2003-01-07',
 '2003-01-08',
 '2003-01-09',
 '2003-01-10',
 '2003-01-13',
 '2003-01-14',
 '2003-01-15',
 '2003-01-16',
 '2003-01-17',
 '2003-01-21',
 '2003-01-22',
 '2003-01-23',
 '2003-01-24',
 '2003-01-27',
 '2003-01-28',
 '2003-01-29',
 '2003-01-30',
 '2003-01-31',
 '2003-02-03',
 '2003-02-04',
 '2003-02-05',
 '2003-02-06',
 '2003-02-07',
 '2003-02-10',
 '2003-02-11',
 '2003-02-12',
 '2003-02-13',
 '2003-02-14',
 '2003-02-18',
 '2003-02-19',
 '2003-02-20',
 '2003-02-21',
 '2003-02-24',
 '2003-02-25',
 '2003-02-26',
 '2003-02-27',
 '2003-02-28',
 '2003-03-03',
 '2003-03-04',
 '2003-03-05',
 '2003-03-06',
 '2003-03-07',
 '2003-03-10',
 '2003-03-11',
 '2003-03-12',
 '2003-03-13',
 '2003-03-14',
 '2003-03-17',
 '2003-03-18',
 '2003-03-19',
 '2003-03-20',
 '2003-03-21',
 '2003-03-24',
 '2003-03-25',
 '2003-03-26',
 '2003-03-27',
 '2003-03-28',
 '2003-03-31',
 '2003-04-01',
 '2003-04-02',
 '2003-04-03',
 '2003-04-04',
 '2003-04-07',
 '2003-04-08',
 '2003-04-09',
 '2003-04-10',
 '2003-04-11',
 '2003-04-14',
 '2003-04-15',
 '2003-04-16',
 '2003-04-17',
 '2003-04-21',
 '2003-04-22',
 '2003-04-23',
 '2003-04-24',
 '2003-04-25',
 '2003-04-28',
 '2003-04-29',
 '2003-04-30',
 '2003-05-01',
 '2003-05-02',
 '2003-05-05',
 '2003-05-06',
 '2003-05-07',
 '2003-05-08',
 '2003-05-09',
 '2003-05-12',
 '2003-05-13',
 '2003-05-14',
 '2003-05-15',
 '2003-05-16',
 '2003-05-19',
 '2003-05-20',
 '2003-05-21',
 '2003-05-22',
 '2003-05-23',
 '2003-05-27',
 '2003-05-28',
 '2003-05-29',
 '2003-05-30',
 '2003-06-02',
 '2003-06-03',
 '2003-06-04',
 '2003-06-05',
 '2003-06-06',
 '2003-06-09',
 '2003-06-10',
 '2003-06-11',
 '2003-06-12',
 '2003-06-13',
 '2003-06-16',
 '2003-06-17',
 '2003-06-18',
 '2003-06-19',
 '2003-06-20',
 '2003-06-23',
 '2003-06-24',
 '2003-06-25',
 '2003-06-26',
 '2003-06-27',
 '2003-06-30',
 '2003-07-01',
 '2003-07-02',
 '2003-07-03',
 '2003-07-07',
 '2003-07-08',
 '2003-07-09',
 '2003-07-10',
 '2003-07-11',
 '2003-07-14',
 '2003-07-15',
 '2003-07-16',
 '2003-07-17',
 '2003-07-18',
 '2003-07-21',
 '2003-07-22',
 '2003-07-23',
 '2003-07-24',
 '2003-07-25',
 '2003-07-28',
 '2003-07-29',
 '2003-07-30',
 '2003-07-31',
 '2003-08-01',
 '2003-08-04',
 '2003-08-05',
 '2003-08-06',
 '2003-08-07',
 '2003-08-08',
 '2003-08-11',
 '2003-08-12',
 '2003-08-13',
 '2003-08-14',
 '2003-08-15',
 '2003-08-18',
 '2003-08-19',
 '2003-08-20',
 '2003-08-21',
 '2003-08-22',
 '2003-08-25',
 '2003-08-26',
 '2003-08-27',
 '2003-08-28',
 '2003-08-29',
 '2003-09-02',
 '2003-09-03',
 '2003-09-04',
 '2003-09-05',
 '2003-09-08',
 '2003-09-09',
 '2003-09-10',
 '2003-09-11',
 '2003-09-12',
 '2003-09-15',
 '2003-09-16',
 '2003-09-17',
 '2003-09-18',
 '2003-09-19',
 '2003-09-22',
 '2003-09-23',
 '2003-09-24',
 '2003-09-25',
 '2003-09-26',
 '2003-09-29',
 '2003-09-30',
 '2003-10-01',
 '2003-10-02',
 '2003-10-03',
 '2003-10-06',
 '2003-10-07',
 '2003-10-08',
 '2003-10-09',
 '2003-10-10',
 '2003-10-13',
 '2003-10-14',
 '2003-10-15',
 '2003-10-16',
 '2003-10-17',
 '2003-10-20',
 '2003-10-21',
 '2003-10-22',
 '2003-10-23',
 '2003-10-24',
 '2003-10-27',
 '2003-10-28',
 '2003-10-29',
 '2003-10-30',
 '2003-10-31',
 '2003-11-03',
 '2003-11-04',
 '2003-11-05',
 '2003-11-06',
 '2003-11-07',
 '2003-11-10',
 '2003-11-11',
 '2003-11-12',
 '2003-11-13',
 '2003-11-14',
 '2003-11-17',
 '2003-11-18',
 '2003-11-19',
 '2003-11-20',
 '2003-11-21',
 '2003-11-24',
 '2003-11-25',
 '2003-11-26',
 '2003-11-28',
 '2003-12-01',
 '2003-12-02',
 '2003-12-03',
 '2003-12-04',
 '2003-12-05',
 '2003-12-08',
 '2003-12-09',
 '2003-12-10',
 '2003-12-11',
 '2003-12-12',
 '2003-12-15',
 '2003-12-16',
 '2003-12-17',
 '2003-12-18',
 '2003-12-19',
 '2003-12-22',
 '2003-12-23',
 '2003-12-24',
 '2003-12-26',
 '2003-12-29',
 '2003-12-30',
 '2003-12-31',
 '2004-01-02',
 '2004-01-05',
 '2004-01-06',
 '2004-01-07',
 '2004-01-08',
 '2004-01-09',
 '2004-01-12',
 '2004-01-13',
 '2004-01-14',
 '2004-01-15',
 '2004-01-16',
 '2004-01-20',
 '2004-01-21',
 '2004-01-22',
 '2004-01-23',
 '2004-01-26',
 ...]

In [96]:
train = df[df["date"] < "2022-01-01"].copy()

val = df[
    (df["date"] >= "2022-01-01") &
    (df["date"] < "2023-01-01")
].copy()

test = df[df["date"] >= "2023-01-01"].copy()

In [97]:
test.head()

,date,open,high,low,close,volume,symbol,return,ma20,volatility,target_open,target_high,target_low,target_close
5787,2023-01-03,148.004774,149.144320,144.605607,146.134735,1414300.0,A,0.002606,147.193403,0.014612,147.702822,149.056642,146.329533,147.722305
5788,2023-01-04,147.702822,149.056642,146.329533,147.722305,1247400.0,A,0.010864,147.154317,0.014263,146.095797,149.085899,144.897816,148.150879
5789,2023-01-05,146.095797,149.085899,144.897816,148.150879,1714600.0,A,0.002901,147.202305,0.014128,150.342290,150.615001,139.287704,143.826416
5790,2023-01-06,150.342290,150.615001,139.287704,143.826416,2445000.0,A,-0.029190,146.918340,0.015103,145.793825,147.342437,143.368631,143.631607
5791,2023-01-09,145.793825,147.342437,143.368631,143.631607,1269600.0,A,-0.001354,146.500637,0.014472,146.271076,151.501314,144.878303,151.189636

In [98]:
print(train.shape)
print(val.shape)
print(test.shape)

print(train["date"].min(), train["date"].max())
print(val["date"].min(), val["date"].max())
print(test["date"].min(), test["date"].max())

(2358199, 14)
(123963, 14)
(436620, 14)
2000-02-01 2021-12-31
2022-01-03 2022-12-30
2023-01-03 2026-07-01

In [99]:
features = [
    "open",
    "high",
    "low",
    "close",
    "volume",
    "return",
    "ma20",
    "volatility"
]

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
train[features]=scaler.fit_transform(train[features])
val[features]=scaler.transform(val[features])
test[features]=scaler.transform(test[features])

In [101]:
print(train[features].describe().round(5))

               open          high           low         close        volume  \
count  2.358199e+06  2.358199e+06  2.358199e+06  2.358199e+06  2.358199e+06
mean   0.000000e+00  0.000000e+00  0.000000e+00 -0.000000e+00  0.000000e+00
std    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00
min   -4.474500e-01 -4.469900e-01 -4.477100e-01 -4.473000e-01 -1.740900e-01
25%   -3.246800e-01 -3.239900e-01 -3.252100e-01 -3.245700e-01 -1.563800e-01
50%   -2.058200e-01 -2.054400e-01 -2.061300e-01 -2.057800e-01 -1.313300e-01
75%    3.016000e-02  2.973000e-02  3.050000e-02  3.009000e-02 -6.922000e-02
max    5.245468e+01  5.183823e+01  5.227694e+01  5.226639e+01  1.789148e+02

             return          ma20    volatility
count  2.358199e+06  2.358199e+06  2.358199e+06
mean   0.000000e+00  0.000000e+00  0.000000e+00
std    1.000000e+00  1.000000e+00  1.000000e+00
min   -2.871666e+01 -4.487400e-01 -1.400220e+00
25%   -4.054900e-01 -3.252400e-01 -5.998800e-01
50%   -7.860000e-03 -2.058900e-01 -2.773600e-01
75%    3.963400e-01  3.038000e-02  2.476100e-01
max    4.311202e+01  5.122098e+01  2.270487e+01

In [102]:
%pip install xgboost

Requirement already satisfied: xgboost in c:\Users\Dell\anaconda3\envs\ml\Lib\site-packages (3.3.0)
Requirement already satisfied: numpy in c:\Users\Dell\anaconda3\envs\ml\Lib\site-packages (from xgboost) (2.5.1)
Requirement already satisfied: scipy in c:\Users\Dell\anaconda3\envs\ml\Lib\site-packages (from xgboost) (1.18.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: There was an error checking the latest version of pip.

In [103]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

In [104]:
l_r=LinearRegression()
r_f=RandomForestRegressor()
xgB=XGBRegressor()

In [105]:
targets = [
    "target_open",
    "target_high",
    "target_low",
    "target_close"
]

In [106]:
X_train=train[features]
Y_train=train[targets]
X_val=val[features]
Y_val=val[targets]
X_test=test[features]
Y_test=test[targets]
print("checked")

checked

In [107]:
l_r.fit(X_train,Y_train)
lr_pred=l_r.predict(X_test)
print("checked")

checked

In [108]:
from sklearn.metrics import accuracy_score,mean_absolute_error,mean_squared_error,r2_score
print("checked")

checked

In [109]:
# mse_lr=mean_squared_error(Y_test,lr_pred)
# mae_lr=mean_absolute_error(Y_test,lr_pred)
# rmse_lr=np.sqrt(mse_lr)
# r2_lr=r2_score(Y_test,lr_pred)
# print(f"MAE  : {mae_lr:.4f}")
# print(f"RMSE : {rmse_lr:.4f}")
# print(f"R²   : {r2_lr:.4f}")
# print("-"*40)


# print("checked")

In [110]:
# xgb = XGBRegressor(
#     n_estimators=500,
#     learning_rate=0.05,
#     verbosity=1,
#     eval_metric="rmse"
# )
# xgb.fit(
#     X_train,
#     Y_train,
#     eval_set=[(X_val, Y_val)],
#     verbose=True
# )

In [111]:
# xgb_pred=xgb.predict(X_test)
# print("checked")

In [112]:
# mse_xgb=mean_squared_error(Y_test,xgb_pred)
# mae_xgb=mean_absolute_error(Y_test,xgb_pred)
# rmse_xgb=np.sqrt(mse_xgb)
# r2_xgb=r2_score(Y_test,xgb_pred)
# print(f"MAE  : {mae_xgb:.4f}")
# print(f"RMSE : {rmse_xgb:.4f}")
# print(f"R²   : {r2_xgb:.4f}")
# print("-"*40)


# print("checked")

In [113]:
seq_targets = [
    "open",
    "high",
    "low",
    "close"
]

In [114]:
from torch.utils.data import DataLoader,Dataset

In [115]:
for _, stock_df in df.groupby("symbol"):

    X = stock_df[features].to_numpy(dtype=np.float32)
    y = stock_df[targets].to_numpy(dtype=np.float32)

    print(X.shape, y.shape)

(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3374, 8) (3374, 4)
(1374, 8) (1374, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6254, 8) (6254, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(5616, 8) (5616, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6372, 8) (6372, 4)
(6643, 8) (6643, 4)
(3152, 8) (3152, 4)
(6643, 8) (6643, 4)
(3532, 8) (3532, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(5210, 8) (5210, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3015, 8) (3015, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3816, 8) (3816, 4)
(1289, 8) (1289, 4)
(3654, 8) (3654, 4)
(6643, 8) (6643, 4)
(3039, 8) (3039, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4231, 8) (4231, 4)
(6643, 8) (6643, 4)
(4556, 8) (4556, 4)
(6275, 8) (6275, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6244, 8) (6244, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(5265, 8) (5265, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4830, 8) (4830, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4766, 8) (4766, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(1559, 8) (1559, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4016, 8) (4016, 4)
(5529, 8) (5529, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3252, 8) (3252, 4)
(1096, 8) (1096, 4)
(5234, 8) (5234, 4)
(2939, 8) (2939, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4127, 8) (4127, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(5908, 8) (5908, 4)
(5119, 8) (5119, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6155, 8) (6155, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(1290, 8) (1290, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3888, 8) (3888, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6523, 8) (6523, 4)
(5521, 8) (5521, 4)
(1753, 8) (1753, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(1765, 8) (1765, 4)
(2286, 8) (2286, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4801, 8) (4801, 4)
(1375, 8) (1375, 4)
(6643, 8) (6643, 4)
(1684, 8) (1684, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(2461, 8) (2461, 4)
(4161, 8) (4161, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(5431, 8) (5431, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(1811, 8) (1811, 4)
(5508, 8) (5508, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(5317, 8) (5317, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4633, 8) (4633, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6186, 8) (6186, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6489, 8) (6489, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6585, 8) (6585, 4)
(6643, 8) (6643, 4)
(1333, 8) (1333, 4)
(6643, 8) (6643, 4)
(5249, 8) (5249, 4)
(5484, 8) (5484, 4)
(6643, 8) (6643, 4)
(3427, 8) (3427, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6274, 8) (6274, 4)
(6642, 8) (6642, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(1816, 8) (1816, 4)
(1817, 8) (1817, 4)
(6643, 8) (6643, 4)
(4913, 8) (4913, 4)
(4158, 8) (4158, 4)
(2492, 8) (2492, 4)
(6643, 8) (6643, 4)
(2810, 8) (2810, 4)
(6643, 8) (6643, 4)
(867, 8) (867, 4)
(6643, 8) (6643, 4)
(547, 8) (547, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3906, 8) (3906, 4)
(4101, 8) (4101, 4)
(5481, 8) (5481, 4)
(5481, 8) (5481, 4)
(6643, 8) (6643, 4)
(6382, 8) (6382, 4)
(6406, 8) (6406, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3830, 8) (3830, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3822, 8) (3822, 4)
(3135, 8) (3135, 4)
(6643, 8) (6643, 4)
(1216, 8) (1216, 4)
(2670, 8) (2670, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(2408, 8) (2408, 4)
(4800, 8) (4800, 4)
(6643, 8) (6643, 4)
(5166, 8) (5166, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(2346, 8) (2346, 4)
(6643, 8) (6643, 4)
(3286, 8) (3286, 4)
(2276, 8) (2276, 4)
(6643, 8) (6643, 4)
(6528, 8) (6528, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4546, 8) (4546, 4)
(6643, 8) (6643, 4)
(2921, 8) (2921, 4)
(2744, 8) (2744, 4)
(6643, 8) (6643, 4)
(3995, 8) (3995, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3848, 8) (3848, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(772, 8) (772, 4)
(6643, 8) (6643, 4)
(4936, 8) (4936, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(2731, 8) (2731, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4742, 8) (4742, 4)
(6643, 8) (6643, 4)
(5399, 8) (5399, 4)
(4049, 8) (4049, 4)
(5142, 8) (5142, 4)
(5036, 8) (5036, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6279, 8) (6279, 4)
(6643, 8) (6643, 4)
(6578, 8) (6578, 4)
(3529, 8) (3529, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3756, 8) (3756, 4)
(5416, 8) (5416, 4)
(6643, 8) (6643, 4)
(1880, 8) (1880, 4)
(6643, 8) (6643, 4)
(6518, 8) (6518, 4)
(6643, 8) (6643, 4)
(4664, 8) (4664, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3362, 8) (3362, 4)
(6019, 8) (6019, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6045, 8) (6045, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3500, 8) (3500, 4)
(5660, 8) (5660, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3258, 8) (3258, 4)
(3258, 8) (3258, 4)
(3979, 8) (3979, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6560, 8) (6560, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(1559, 8) (1559, 4)
(6643, 8) (6643, 4)
(3486, 8) (3486, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6191, 8) (6191, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6625, 8) (6625, 4)
(6643, 8) (6643, 4)
(1424, 8) (1424, 4)
(4582, 8) (4582, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4793, 8) (4793, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6155, 8) (6155, 4)
(6643, 8) (6643, 4)
(5154, 8) (5154, 4)
(3555, 8) (3555, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(2744, 8) (2744, 4)
(150, 8) (150, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4825, 8) (4825, 4)
(6643, 8) (6643, 4)
(326, 8) (326, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(548, 8) (548, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(5905, 8) (5905, 4)
(6643, 8) (6643, 4)
(4518, 8) (4518, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(2977, 8) (2977, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(5086, 8) (5086, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4772, 8) (4772, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4811, 8) (4811, 4)
(6643, 8) (6643, 4)
(6450, 8) (6450, 4)
(3894, 8) (3894, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4006, 8) (4006, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(2437, 8) (2437, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(5112, 8) (5112, 4)
(1775, 8) (1775, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4679, 8) (4679, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(4580, 8) (4580, 4)
(3175, 8) (3175, 4)
(2115, 8) (2115, 4)
(6643, 8) (6643, 4)
(667, 8) (667, 4)
(6643, 8) (6643, 4)
(4188, 8) (4188, 4)
(6643, 8) (6643, 4)
(1968, 8) (1968, 4)
(6643, 8) (6643, 4)
(2427, 8) (2427, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(5258, 8) (5258, 4)
(3427, 8) (3427, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(6280, 8) (6280, 4)
(6643, 8) (6643, 4)
(5937, 8) (5937, 4)
(6643, 8) (6643, 4)
(6643, 8) (6643, 4)
(3679, 8) (3679, 4)
(2647, 8) (2647, 4)
(6643, 8) (6643, 4)
(6250, 8) (6250, 4)
(6643, 8) (6643, 4)
(3353, 8) (3353, 4)

In [116]:
import numpy as np
import torch
from torch.utils.data import Dataset

class StockDataset(Dataset):

    def __init__(self, df, features, targets, seq_len=60):

        self.seq_len = seq_len
        self.features = features
        self.targets = targets

        self.stock_data = {}
        self.indices = []

        for symbol, stock_df in df.groupby("symbol"):

            stock_df = stock_df.sort_values("date")

            X = stock_df[features].to_numpy(dtype=np.float32)
            Y = stock_df[targets].to_numpy(dtype=np.float32)

            self.stock_data[symbol] = (X, Y)

            for start in range(len(stock_df) - seq_len):
                self.indices.append((symbol, start))

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):

        symbol, start = self.indices[idx]

        X, Y = self.stock_data[symbol]

        x = X[start:start + self.seq_len]
        y = Y[start + self.seq_len]

        return (
            torch.from_numpy(x),
            torch.from_numpy(y)
        )

In [ ]:
train_dataset = StockDataset(train, features, seq_targets, seq_len=60)
val_dataset = StockDataset(val, features, seq_targets, seq_len=60)
test_dataset = StockDataset(test, features, seq_targets, seq_len=60)

In [118]:
from torch.utils.data import DataLoader

train_loader = DataLoader(
    train_dataset,
    batch_size=512,
    shuffle=True,
    num_workers=0,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=512,
    shuffle=False,
    num_workers=0,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=512,
    shuffle=False,
    num_workers=0,
    pin_memory=True
)

In [119]:
import torch

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.11.0+cu128
12.8
True
NVIDIA GeForce RTX 3050 Laptop GPU

In [120]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 3050 Laptop GPU

In [121]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

cuda

In [122]:
import torch
import torch.nn as nn

In [123]:
class LSTMModel(nn.Module):

    def __init__(self, input_size=8, hidden_size=128, num_layers=2, output_size=4):
        super().__init__()

        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True
        )

        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):

        output, (hn, cn) = self.lstm(x)

        # Last time step
        x = output[:, -1, :]

        return self.fc(x)

In [124]:
model = LSTMModel().to(device)

In [125]:
criterion = nn.MSELoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=1e-3
)

In [126]:
%pip install tqdm

Requirement already satisfied: tqdm in c:\Users\Dell\anaconda3\envs\ml\Lib\site-packages (4.68.4)
Requirement already satisfied: colorama in c:\Users\Dell\anaconda3\envs\ml\Lib\site-packages (from tqdm) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

WARNING: There was an error checking the latest version of pip.

In [127]:
from tqdm import tqdm

In [128]:
import os


os.makedirs("checkpoints", exist_ok=True)

epochs = 50

train_losses = []
val_losses = []

best_val_loss = float("inf")

for epoch in range(epochs):

    # ==========================
    # Training
    # ==========================
    model.train()
    running_loss = 0.0

    progress_bar = tqdm(
        train_loader,
        desc=f"Epoch {epoch+1}/{epochs}",
        leave=True
    )

    for X_batch, y_batch in progress_bar:

        X_batch = X_batch.to(device, non_blocking=True)
        y_batch = y_batch.to(device, non_blocking=True)

        optimizer.zero_grad()

        pred = model(X_batch)

        loss = criterion(pred, y_batch)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

        progress_bar.set_postfix(loss=f"{loss.item():.4f}")

    avg_train_loss = running_loss / len(train_loader)
    train_losses.append(avg_train_loss)

    # ==========================
    # Validation
    # ==========================
    model.eval()
    running_val_loss = 0.0

    with torch.no_grad():

        for X_batch, y_batch in val_loader:

            X_batch = X_batch.to(device, non_blocking=True)
            y_batch = y_batch.to(device, non_blocking=True)

            pred = model(X_batch)

            loss = criterion(pred, y_batch)

            running_val_loss += loss.item()

    avg_val_loss = running_val_loss / len(val_loader)
    val_losses.append(avg_val_loss)

    print(
        f"Epoch {epoch+1}/{epochs} | "
        f"Train Loss: {avg_train_loss:.5f} | "
        f"Val Loss: {avg_val_loss:.5f}"
    )

    checkpoint = {
        "epoch": epoch + 1,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "train_loss": avg_train_loss,
        "val_loss": avg_val_loss,
    }


    torch.save(
        checkpoint,
        "checkpoints/latest_checkpoint.pth"
    )


    if avg_val_loss < best_val_loss:

        best_val_loss = avg_val_loss

        torch.save(
            checkpoint,
            "checkpoints/best_model.pth"
        )

        print(f"✓ New best model saved! Val Loss = {best_val_loss:.5f}")


history = pd.DataFrame({
    "epoch": range(1, epochs + 1),
    "train_loss": train_losses,
    "val_loss": val_losses
})

history.to_csv(
    "checkpoints/training_history.csv",
    index=False
)

print("Training Complete.")

Epoch 1/50: 100%|██████████| 4549/4549 [02:49<00:00, 26.77it/s, loss=1118.4161]

Epoch 1/50 | Train Loss: 9305.47482 | Val Loss: 50368.00294
✓ New best model saved! Val Loss = 50368.00294

Epoch 2/50: 100%|██████████| 4549/4549 [02:56<00:00, 25.72it/s, loss=921.5882]

Epoch 2/50 | Train Loss: 6057.01917 | Val Loss: 70629.51605

Epoch 3/50: 100%|██████████| 4549/4549 [03:08<00:00, 24.13it/s, loss=960.7471]

Epoch 3/50 | Train Loss: 10774.00486 | Val Loss: 58686.26349

Epoch 4/50: 100%|██████████| 4549/4549 [03:05<00:00, 24.52it/s, loss=874.7180]

Epoch 4/50 | Train Loss: 9219.09753 | Val Loss: 55499.13269

Epoch 5/50: 100%|██████████| 4549/4549 [03:09<00:00, 24.02it/s, loss=1.8492]

Epoch 5/50 | Train Loss: 8388.79868 | Val Loss: 53427.81498

Epoch 6/50:   4%|▎         | 165/4549 [00:06<03:04, 23.78it/s, loss=790.4619]

KeyboardInterrupt:

In [ ]:
class GRUModel(nn.Module):
    
    def __init__(self,input_size=8,hidden_size=128,output_size=4, num_layers=2):
        super().__init__()
        
        self.gru=nn.GRU(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True
        )
        
        self.fc=nn.Linear(in_features=hidden_size,out_features=output_size)
        
    def forward(self,x):
        output,hn=self.gru(x)
        x=output[:,-1,:]
        
        return self.fc(x)